/** @type {import("prettier").Config} */

module.exports = {
  trailingComma: "all",
  printWidth: 100,
  importOrderSeparation: true,
  importOrder: [
    "<THIRD_PARTY_MODULES>",
    "^@sikka/(.*)$",
    "^@/ui/(.*)$",
    "^@/root/(.*)$",
    "^@/utils/(.*)$",
    "^@/hooks/(.*)$",
    "^@/components/(.*)$",
    "^@/forms/(.*)$",
    "^@/tables/(.*)$",
    "^@/lib/(.*)$",
    "^@/services/(.*)$",
    "^@/types/(.*)$",
    "^@/shared/(.*)$",
    "^@/for_invoices/(.*)$",
    "^@/data/(.*)$",
    "^@/api/(.*)$",
    "^@/tags/(.*)$",
    "^@/office/(.*)$",
    "^@/job/(.*)$",
    "^@/applicant/(.*)$",
    "^@/branch/(.*)$",
    "^@/client/(.*)$",
    "^@/company/(.*)$",
    "^@/dashboard/(.*)$",
    "^@/department/(.*)$",
    "^@/employee/(.*)$",
    "^@/employee-request/(.*)$",
    "^@/expense/(.*)$",
    "^@/invoice/(.*)$",
    "^@/job-listing/(.*)$",
    "^@/product/(.*)$",
    "^@/purchase/(.*)$",
    "^@/quote/(.*)$",
    "^@/role/(.*)$",
    "^@/salary/(.*)$",
    "^@/sale/(.*)$",
    "^@/setting/(.*)$",
    "^@/user/(.*)$",
    "^@/vendor/(.*)$",
    "^@/warehouse/(.*)$",

    "^@/(.*)$",
    "^[./]",
  ],
  plugins: ["@trivago/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
};
