import {
  Building2,
  Briefcase,
  FileInput,
  FileText,
  Filter,
  LayoutDashboard,
  ShieldPlus,
  Store,
  UserRoundCog,
  Users,
  Warehouse,
  CircleDollarSign,
  SaudiRiyal,
  Settings,
  ShoppingCart,
  BriefcaseBusiness,
  Globe,
  Server,
  Link,
  TableOfContents,
  BarChart,
  Car,
  Truck,
} from "lucide-react";

const ModulesOptions = {
  dashboard: {
    icon: LayoutDashboard,
    label: "Titles.Dashboard",
    translationKey: "Titles.Dashboard",
    url: "/dashboard",
  },
  analytics: {
    icon: BarChart,
    label: "Titles.Analytics",
    translationKey: "Titles.Analytics",
    url: "/analytics",
  },
  activity_logs: {
    icon: TableOfContents,
    label: "Titles.ActivityLogs",
    translationKey: "Titles.ActivityLogs",
    url: "/activity",
  },
  sales: {
    icon: SaudiRiyal,
    label: "Titles.Sales",
    translationKey: "Titles.Sales",
    url: "/sales",
  },
  job_listings: {
    icon: Briefcase,
    label: "Titles.JobListings",
    translationKey: "Titles.JobListings",
    url: "/job_listings",
  },
  companies: {
    icon: Building2,
    label: "Titles.Companies",
    translationKey: "Titles.Companies",
    url: "/companies",
  },
  roles: {
    icon: ShieldPlus,
    label: "Titles.Roles",
    translationKey: "Titles.Roles",
    url: "/roles",
  },
  applicants: {
    icon: Users,
    label: "Titles.Applicants",
    translationKey: "Titles.Applicants",
    url: "/applicants",
  },
  purchases: {
    icon: ShoppingCart,
    label: "Titles.Purchases",
    translationKey: "Titles.Purchases",
    url: "/purchases",
  },
  clients: {
    icon: Users,
    label: "Titles.Clients",
    translationKey: "Titles.Clients",
    url: "/clients",
  },
  vendors: {
    icon: Users,
    label: "Titles.Vendors",
    translationKey: "Titles.Vendors",
    url: "/vendors",
  },
  invoices: {
    icon: FileText,
    label: "Titles.Invoices",
    translationKey: "Titles.Invoices",
    url: "/invoices",
  },
  quotes: {
    icon: FileInput,
    label: "Titles.Quotes",
    translationKey: "Titles.Quotes",
    url: "/quotes",
  },
  products: {
    icon: Filter,
    label: "Titles.Products",
    translationKey: "Titles.Products",
    url: "/products",
  },
  offices: {
    icon: Building2,
    label: "Titles.Offices",
    translationKey: "Titles.Offices",
    url: "/offices",
  },
  warehouses: {
    icon: Warehouse,
    label: "Titles.Warehouses",
    translationKey: "Titles.Warehouses",
    url: "/warehouses",
  },
  branches: {
    icon: Store,
    label: "Titles.Branches",
    translationKey: "Titles.Branches",
    url: "/branches",
  },
  employees: {
    icon: BriefcaseBusiness,
    label: "Titles.Employees",
    translationKey: "Titles.Employees",
    url: "/employees",
  },
  departments: {
    icon: Building2,
    label: "Titles.Departments",
    translationKey: "Titles.Departments",
    url: "/departments",
  },
  employee_requests: {
    icon: Briefcase,
    label: "Titles.EmployeeRequests",
    translationKey: "Titles.EmployeeRequests",
    url: "/employee_requests",
  },
  jobs: {
    icon: Briefcase,
    label: "Titles.Jobs",
    translationKey: "Titles.Jobs",
    url: "/jobs",
  },
  expenses: {
    icon: CircleDollarSign,
    label: "Titles.Expenses",
    translationKey: "Titles.Expenses",
    url: "/expenses",
  },
  salaries: {
    icon: SaudiRiyal,
    label: "Titles.Salaries",
    translationKey: "Titles.Salaries",
    url: "/salaries",
  },
  users: {
    icon: UserRoundCog,
    label: "Titles.Users",
    translationKey: "Titles.Users",
    url: "/users",
  },
  settings: {
    icon: Settings,
    label: "Titles.Settings",
    translationKey: "Titles.Settings",
    url: "/settings",
  },
  internet: {
    label: "Titles.Internet",
    translationKey: "Titles.Internet",
    url: "/internet",
  },
  websites: {
    icon: Globe,
    label: "Titles.Websites",
    translationKey: "Titles.Websites",
    url: "/websites",
  },
  servers: {
    icon: Server,
    label: "Titles.Servers",
    translationKey: "Titles.Servers",
    url: "/servers",
  },
  domains: {
    icon: Link,
    label: "Titles.Domains",
    translationKey: "Titles.Domains",
    url: "/domains",
  },
  online_stores: {
    icon: Store,
    label: "Titles.OnlineStores",
    translationKey: "Titles.OnlineStores",
    url: "/online_stores",
  },
  cars: {
    icon: Car,
    label: "Titles.Cars",
    translationKey: "Titles.Cars",
    url: "/cars",
  },
  trucks: {
    icon: Truck,
    label: "Titles.Trucks",
    translationKey: "Titles.Trucks",
    url: "/trucks",
  },
};

const currencies = [
  "sar",
  "usd",
  "bhd",
  "kwd",
  "qar",
  "aed",
  "omr",
  "try",
  "iqd",
  "eur",
  "gbp",
  "jpy",
] as const;

export { ModulesOptions, currencies };
