import {
  Building2,
  Briefcase,
  FileInput,
  FileText,
  Filter,
  LayoutDashboard,
  ShieldPlus,
  Store,
  UserRoundCog,
  Users,
  Warehouse,
  CircleDollarSign,
  SaudiRiyal,
  Settings,
  ShoppingCart,
  BriefcaseBusiness,
} from "lucide-react";

const ModulesOptions = {
  dashboard: {
    icon: LayoutDashboard,
    label: "Dashboard.title",
    translationKey: "Dashboard.title",
    url: "/dashboard",
  },
  sales: {
    icon: SaudiRiyal,
    label: "Sales.title",
    translationKey: "Sales.title",
    url: "/sales",
  },
  job_listings: {
    icon: Briefcase,
    label: "JobListings.title",
    translationKey: "JobListings.title",
    url: "/jobs/listings",
  },
  companies: {
    icon: Building2,
    label: "Companies.title",
    translationKey: "Companies.title",
    url: "/companies",
  },
  roles: {
    icon: ShieldPlus,
    label: "Roles.title",
    translationKey: "Roles.title",
    url: "/roles",
  },
  applicants: {
    icon: Users,
    label: "Applicants.title",
    translationKey: "Applicants.title",
    url: "/applicants",
  },
  purchases: {
    icon: ShoppingCart,
    label: "Purchases.title",
    translationKey: "Purchases.title",
    url: "/purchases",
  },
  clients: {
    icon: Users,
    label: "Clients.title",
    translationKey: "Clients.title",
    url: "/clients",
  },
  vendors: {
    icon: Users,
    label: "Vendors.title",
    translationKey: "Vendors.title",
    url: "/vendors",
  },
  invoices: {
    icon: FileText,
    label: "Invoices.title",
    translationKey: "Invoices.title",
    url: "/invoices",
  },
  quotes: {
    icon: FileInput,
    label: "Quotes.title",
    translationKey: "Quotes.title",
    url: "/quotes",
  },
  products: {
    icon: Filter,
    label: "Products.title",
    translationKey: "Products.title",
    url: "/products",
  },
  offices: {
    icon: Building2,
    label: "Offices.title",
    translationKey: "Offices.title",
    url: "/offices",
  },
  warehouses: {
    icon: Warehouse,
    label: "Warehouses.title",
    translationKey: "Warehouses.title",
    url: "/warehouses",
  },
  branches: {
    icon: Store,
    label: "Branches.title",
    translationKey: "Branches.title",
    url: "/branches",
  },
  employees: {
    icon: BriefcaseBusiness,
    label: "Employees.title",
    translationKey: "Employees.title",
    url: "/employees",
  },
  departments: {
    icon: Building2,
    label: "Departments.title",
    translationKey: "Departments.title",
    url: "/departments",
  },
  employee_requests: {
    icon: Briefcase,
    label: "EmployeeRequests.title",
    translationKey: "EmployeeRequests.title",
    url: "/employee-requests",
  },
  jobs: {
    icon: Briefcase,
    label: "Jobs.title",
    translationKey: "Jobs.title",
    url: "/jobs",
  },
  expenses: {
    icon: CircleDollarSign,
    label: "Expenses.title",
    translationKey: "Expenses.title",
    url: "/expenses",
  },
  salaries: {
    icon: SaudiRiyal,
    label: "Salaries.title",
    translationKey: "Salaries.title",
    url: "/salaries",
  },
  users: {
    icon: UserRoundCog,
    label: "Users.title",
    translationKey: "Users.title",
    url: "/users",
  },
  settings: {
    icon: Settings,
    label: "Settings.title",
    translationKey: "Settings.title",
    url: "/settings",
  },
};

export { ModulesOptions };
