services:
  admin-portal:
    build:
      context: .
      dockerfile: Dockerfile.admin
      args:
        - DIRECTUS_URL=${DIRECTUS_URL}
        - DIRECTUS_TOKEN=${DIRECTUS_TOKEN}
        - DATABASE_URL=${DATABASE_URL}
        - NEXT_PUBLIC_STRIPE_PRODUCT_ID=${NEXT_PUBLIC_STRIPE_PRODUCT_ID}
        - NEXT_PUBLIC_STRIPE_SECRET_KEY=${NEXT_PUBLIC_STRIPE_SECRET_KEY}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    environment:
      - NODE_ENV=production
      - PORT=3037
      - HOSTNAME=0.0.0.0
      - SERVICE_FQDN_SIKKA=/
      - DIRECTUS_URL=${DIRECTUS_URL}
      - DIRECTUS_TOKEN=${DIRECTUS_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_STRIPE_PRODUCT_ID=${NEXT_PUBLIC_STRIPE_PRODUCT_ID}
      - NEXT_PUBLIC_STRIPE_SECRET_KEY=${NEXT_PUBLIC_STRIPE_SECRET_KEY}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3037:3037"
    restart: unless-stopped 