import { PuklaThemeProps } from "./types";

// Validation
export const DOMAIN_REGEX = /^[a-zA-Z0-9-]+$/; // Allows letters, numbers, and hyphens
export const MAX_SLUG_LENGTH = 32;

export const CACHE_KEY = (user_id: string) => `user_cache_${user_id}`;
export const FREE_PLAN_ID = "price_1QfPy8CVtUnAWEKBdr1JAb5w";
export const TANAD_PRODUCT_ID = process.env.NEXT_PUBLIC_STRIPE_PRODUCT_ID;
export const fakeAnalyticsData = [
  {
    country: "Saudi Arabia",
    city: "Riyadh",
    mobile: 847,
    desktop: 392,
    total: 1239,
  },
  {
    country: "Bahrain",
    city: "Manama",
    mobile: 283,
    desktop: 156,
    total: 439,
  },
  {
    country: "Kuwait",
    city: "Kuwait City",
    mobile: 412,
    desktop: 245,
    total: 657,
  },
  {
    country: "United Arab Emirates",
    city: "Dubai",
    mobile: 1256,
    desktop: 864,
    total: 2120,
  },
  {
    country: "Qatar",
    city: "Doha",
    mobile: 734,
    desktop: 428,
    total: 1162,
  },
  {
    country: "Saudi Arabia",
    city: "Jeddah",
    mobile: 623,
    desktop: 289,
    total: 912,
  },
  {
    country: "Oman",
    city: "Muscat",
    mobile: 342,
    desktop: 187,
    total: 529,
  },
];

export const blacklist = [
  "users",
  "user",
  "admins",
  "admin",
  "editor",
  "billing",
  "analytics",
  "analytic",
  "auth",
  "login",
  "log-in",
  "sign-in",
  "sign-up",
  "register",
  "logout",
  "profile",
  "settings",
  "account",
  "password",
  "email",
  "phone",
  "reset-password",
  "forgot-password",
  "verify-email",
  "verify-phone",
  "verify-password",
  "verify-email-code",
  "verify-phone-code",
  "verify-password-code",
  "theme",
  "themes",
  "feature",
  "features",
  "pricing",
  "contact",
  "contacts",
  "help",
  "report-ip",
  "report",
  "reports",
  "support",
  "terms",
  "privacy",
  "blog",
  "appeal",
  "dashboard",
  "dashboards",
  "appeals",
  "404",
  "sex",
  "porn",
  "adult",
  "nude",
  "nsfw",
  "xxx",
  "butt",
  "boobs",
  "pussy",
  "admin",
  "moderator",
  "mod",
  "root",
  "system",
  "support",
  "help",
  "staff",
  "official",
  "security",
  "test",
  "beta",
  "null",
  "void",
  "undefined",
  "fuck",
  "shit",
  "bitch",
  "asshole",
  "bastard",
  "cunt",
  "dick",
  "pussy",
  "nigger",
  "nigga",
  "faggot",
  "retard",
  "slut",
  "whore",
  "rape",
  "kill",
  "terrorist",
  "isis",
  "hitler",
  "nazi",
  "kkk",
  "pedo",
  "pedophile",
  "scam",
  "fraud",
  "hacker",
  "virus",
  "malware",
  "phish",
  "spam",
  "bot",
  "porn",
  "sex",
  "xxx",
  "cum",
  "suck",
  "blowjob",
  "anal",
  "deepthroat",
  "cock",
  "vagina",
  "boobs",
  "tits",
  "nipples",
  "milf",
  "gay",
  "lesbian",
  "trans",
  "tranny",
  "hooker",
  "escort",
  "stripper",
  "prostitute",
  "suicide",
  "selfharm",
  "cutting",
  "depression",
  "drugs",
  "cocaine",
  "heroin",
  "meth",
  "weed",
  "marijuana",
  "ecstasy",
  "lsd",
  "overdose",
  "alcoholic",
  "drunk",
  "hangover",
  "gambling",
  "casino",
  "lottery",
  "fake",
  "imposter",
  "clone",
  "impersonate",
  "fakeaccount",
  "deepfake",
  "racist",
  "homophobic",
  "bigot",
  "misogynist",
  "childabuse",
  "abuser",
  "domesticviolence",
  "molester",
  "stalker",
];

export const predefinedThemes: PuklaThemeProps[] = [
  {
    theme_name: "Default",
    is_free: true,
    button_color: "#000000",
    text_color: "#000000",
    background_color: "#ffffff",
    button_text_color: "#ffffff",
    button_hover_color: "#000000",
    button_border_color: "#000000",
    link_color: "#000000",
    primary_color: "#000000",
    border_color: "#000000",
    border_radius: "8px",
  },
  {
    theme_name: "Ocean",
    is_free: true,
    button_color: "#2563eb",
    text_color: "#1e3a8a",
    background_color: "#dbeafe",
    button_text_color: "#ffffff",
    button_hover_color: "#1d4ed8",
    button_border_color: "#1d4ed8",
    link_color: "#2563eb",
    primary_color: "#2563eb",
    border_color: "#000000",
    border_radius: "8px",
  },
  {
    theme_name: "Sunset",
    is_free: true,
    button_color: "#ea580c",
    text_color: "#7c2d12",
    background_color: "#ffedd5",
    button_text_color: "#ffffff",
    button_hover_color: "#c2410c",
    button_border_color: "#c2410c",
    link_color: "#ea580c",
    primary_color: "#ea580c",
    border_color: "#000000",
    border_radius: "8px",
  },
  {
    theme_name: "Forest",
    is_free: false,
    button_color: "#166534",
    text_color: "#14532d",
    background_color: "#dcfce7",
    button_text_color: "#ffffff",
    button_hover_color: "#15803d",
    button_border_color: "#15803d",
    link_color: "#166534",
    primary_color: "#166534",
    border_color: "#000000",
    border_radius: "8px",
  },
  {
    theme_name: "Royal",
    is_free: false,
    button_color: "#7e22ce",
    text_color: "#581c87",
    background_color: "#f3e8ff",
    button_text_color: "#ffffff",
    button_hover_color: "#6b21a8",
    button_border_color: "#6b21a8",
    link_color: "#7e22ce",
    primary_color: "#7e22ce",
    border_color: "#000000",
    border_radius: "8px",
  },
  {
    theme_name: "Cherry",
    is_free: false,
    button_color: "#be123c",
    text_color: "#881337",
    background_color: "#ffe4e6",
    button_text_color: "#ffffff",
    button_hover_color: "#9f1239",
    button_border_color: "#9f1239",
    link_color: "#be123c",
    primary_color: "#be123c",
    border_color: "#000000",
    border_radius: "8px",
  },
  {
    theme_name: "Midnight",
    is_free: false,
    button_color: "#1e293b",
    text_color: "#0f172a",
    background_color: "#f1f5f9",
    button_text_color: "#ffffff",
    button_hover_color: "#334155",
    button_border_color: "#334155",
    link_color: "#1e293b",
    primary_color: "#1e293b",
    border_color: "#000000",
    border_radius: "8px",
  },
  {
    theme_name: "Desert",
    is_free: false,
    button_color: "#a16207",
    text_color: "#854d0e",
    background_color: "#fef9c3",
    button_text_color: "#ffffff",
    button_hover_color: "#ca8a04",
    button_border_color: "#ca8a04",
    link_color: "#a16207",
    primary_color: "#a16207",
    border_color: "#000000",
    border_radius: "8px",
  },
  {
    theme_name: "Emerald",
    is_free: false,
    button_color: "#047857",
    text_color: "#065f46",
    background_color: "#d1fae5",
    button_text_color: "#ffffff",
    button_hover_color: "#059669",
    button_border_color: "#059669",
    link_color: "#047857",
    primary_color: "#047857",
    border_color: "#000000",
    border_radius: "8px",
  },
  {
    theme_name: "Rose Gold",
    is_free: false,
    button_color: "#be185d",
    text_color: "#9d174d",
    background_color: "#fdf2f8",
    button_text_color: "#ffffff",
    button_hover_color: "#db2777",
    button_border_color: "#db2777",
    link_color: "#be185d",
    primary_color: "#be185d",
    border_color: "#000000",
    border_radius: "8px",
  },
  {
    theme_name: "Forest",
    is_free: false,
    button_color: "#166534",
    text_color: "#14532d",
    background_color: "#dcfce7",
    button_text_color: "#ffffff",
    button_hover_color: "#15803d",
    button_border_color: "#15803d",
    link_color: "#166534",
    primary_color: "#166534",
    border_color: "#000000",
    border_radius: "8px",
  },
  {
    theme_name: "Autumn",
    is_free: false,
    button_color: "#b45309",
    text_color: "#92400e",
    background_color: "#fff7ed",
    button_text_color: "#ffffff",
    button_hover_color: "#d97706",
    button_border_color: "#d97706",
    link_color: "#b45309",
    primary_color: "#b45309",
    border_color: "#000000",
    border_radius: "8px",
  },
  {
    theme_name: "Slate",
    is_free: false,
    button_color: "#475569",
    text_color: "#334155",
    background_color: "#f8fafc",
    button_text_color: "#ffffff",
    button_hover_color: "#64748b",
    button_border_color: "#64748b",
    link_color: "#475569",
    primary_color: "#475569",
    border_color: "#000000",
    border_radius: "8px",
  },
  {
    theme_name: "Indigo",
    is_free: false,
    button_color: "#4338ca",
    text_color: "#3730a3",
    background_color: "#eef2ff",
    button_text_color: "#ffffff",
    button_hover_color: "#4f46e5",
    button_border_color: "#4f46e5",
    link_color: "#4338ca",
    primary_color: "#4338ca",
    border_color: "#000000",
    border_radius: "8px",
  },
];
