export type JobListing = {
  id: string;
  title: string;
  description: string;
  department: string;
  location: string;
  type: string;
  postedDate: string;
  salary: string;
  responsibilities: string[];
  requirements: string[];
  benefits: string[];
};

export const jobListings: JobListing[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    department: "Engineering",
    type: "Full-time",
    location: "San Francisco, CA (Hybrid)",
    postedDate: "2 days ago",
    salary: "$120,000 - $150,000",
    description:
      "We're looking for a Senior Frontend Developer to join our engineering team. You'll be responsible for building and maintaining our web applications, working closely with designers and backend developers.",
    responsibilities: [
      "Develop and maintain responsive web applications using React and TypeScript",
      "Collaborate with designers to implement UI/UX designs",
      "Write clean, maintainable, and efficient code",
      "Participate in code reviews and mentor junior developers",
      "Optimize applications for maximum speed and scalability",
    ],
    requirements: [
      "5+ years of experience in frontend development",
      "Strong proficiency in React, TypeScript, and modern JavaScript",
      "Experience with state management libraries (Redux, Zustand, etc.)",
      "Knowledge of responsive design and cross-browser compatibility",
      "Familiarity with testing frameworks (Jest, React Testing Library)",
      "Bachelor's degree in Computer Science or related field (or equivalent experience)",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Health, dental, and vision insurance",
      "Flexible work arrangements",
      "Unlimited PTO",
      "401(k) matching",
      "Professional development budget",
    ],
  },
  {
    id: "2",
    title: "Product Manager",
    department: "Product",
    type: "Full-time",
    location: "New York, NY (Remote)",
    postedDate: "1 week ago",
    salary: "$110,000 - $140,000",
    description:
      "We're seeking an experienced Product Manager to help define and execute our product strategy. You'll work closely with engineering, design, and marketing teams to deliver features that delight our users.",
    responsibilities: [
      "Define product requirements and create detailed specifications",
      "Collaborate with engineering and design teams to deliver high-quality products",
      "Conduct market research and competitive analysis",
      "Gather and analyze user feedback to inform product decisions",
      "Track and measure product performance metrics",
    ],
    requirements: [
      "3+ years of experience in product management",
      "Strong analytical and problem-solving skills",
      "Excellent communication and presentation abilities",
      "Experience with agile development methodologies",
      "Bachelor's degree in Business, Computer Science, or related field",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Health, dental, and vision insurance",
      "Remote-first work environment",
      "Unlimited PTO",
      "Home office stipend",
      "Professional development budget",
    ],
  },
  {
    id: "3",
    title: "UX/UI Designer",
    department: "Design",
    type: "Full-time",
    location: "Austin, TX (Hybrid)",
    postedDate: "3 days ago",
    salary: "$90,000 - $120,000",
    description:
      "We're looking for a talented UX/UI Designer to create beautiful, intuitive interfaces for our products. You'll work closely with product managers and engineers to deliver exceptional user experiences.",
    responsibilities: [
      "Create wireframes, prototypes, and high-fidelity designs",
      "Conduct user research and usability testing",
      "Develop and maintain design systems",
      "Collaborate with engineers to implement designs",
      "Stay up-to-date with design trends and best practices",
    ],
    requirements: [
      "3+ years of experience in UX/UI design",
      "Proficiency in design tools (Figma, Sketch, Adobe XD)",
      "Strong portfolio demonstrating your design process",
      "Experience with responsive web design",
      "Knowledge of accessibility standards",
      "Bachelor's degree in Design, HCI, or related field (or equivalent experience)",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Health, dental, and vision insurance",
      "Flexible work arrangements",
      "Unlimited PTO",
      "401(k) matching",
      "Professional development budget",
    ],
  },
  {
    id: "4",
    title: "DevOps Engineer",
    department: "Engineering",
    type: "Full-time",
    location: "Remote",
    postedDate: "5 days ago",
    salary: "$115,000 - $145,000",
    description:
      "We're seeking a DevOps Engineer to help build and maintain our cloud infrastructure. You'll work on automating deployment processes, improving system reliability, and ensuring security best practices.",
    responsibilities: [
      "Design, implement, and maintain CI/CD pipelines",
      "Manage cloud infrastructure on AWS or GCP",
      "Implement monitoring and alerting systems",
      "Automate manual processes to improve efficiency",
      "Collaborate with development teams to resolve operational issues",
    ],
    requirements: [
      "3+ years of experience in DevOps or SRE roles",
      "Strong knowledge of cloud platforms (AWS, GCP, or Azure)",
      "Experience with containerization (Docker, Kubernetes)",
      "Proficiency in scripting languages (Python, Bash)",
      "Familiarity with infrastructure as code (Terraform, CloudFormation)",
      "Bachelor's degree in Computer Science or related field (or equivalent experience)",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Health, dental, and vision insurance",
      "Remote-first work environment",
      "Unlimited PTO",
      "Home office stipend",
      "Professional development budget",
    ],
  },
  {
    id: "5",
    title: "Marketing Specialist",
    department: "Marketing",
    type: "Full-time",
    location: "Chicago, IL (Hybrid)",
    postedDate: "1 week ago",
    salary: "$70,000 - $90,000",
    description:
      "We're looking for a Marketing Specialist to help grow our brand and acquire new customers. You'll be responsible for creating and executing marketing campaigns across various channels.",
    responsibilities: [
      "Plan and execute marketing campaigns across digital channels",
      "Create engaging content for social media, email, and blog",
      "Analyze campaign performance and optimize for better results",
      "Collaborate with design team on marketing materials",
      "Stay up-to-date with marketing trends and best practices",
    ],
    requirements: [
      "2+ years of experience in digital marketing",
      "Strong understanding of social media platforms and best practices",
      "Experience with email marketing and marketing automation tools",
      "Analytical mindset with ability to derive insights from data",
      "Excellent written and verbal communication skills",
      "Bachelor's degree in Marketing, Communications, or related field",
    ],
    benefits: [
      "Competitive salary",
      "Health, dental, and vision insurance",
      "Flexible work arrangements",
      "Generous PTO",
      "401(k) matching",
      "Professional development opportunities",
    ],
  },
  {
    id: "6",
    title: "Customer Success Manager",
    department: "Customer Success",
    type: "Full-time",
    location: "Denver, CO (Remote)",
    postedDate: "2 weeks ago",
    salary: "$80,000 - $100,000",
    description:
      "We're seeking a Customer Success Manager to ensure our customers achieve their goals using our product. You'll be the primary point of contact for a portfolio of customers, helping them maximize value and driving retention.",
    responsibilities: [
      "Onboard new customers and ensure successful product adoption",
      "Develop and maintain strong relationships with key stakeholders",
      "Identify upsell and cross-sell opportunities",
      "Monitor customer health metrics and address issues proactively",
      "Gather customer feedback and share insights with product team",
    ],
    requirements: [
      "3+ years of experience in customer success or account management",
      "Strong interpersonal and communication skills",
      "Problem-solving mindset with ability to navigate complex situations",
      "Experience with CRM software (Salesforce, HubSpot)",
      "Bachelor's degree in Business, Communications, or related field",
    ],
    benefits: [
      "Competitive salary and commission structure",
      "Health, dental, and vision insurance",
      "Remote-first work environment",
      "Unlimited PTO",
      "Home office stipend",
      "Professional development budget",
    ],
  },
  {
    id: "7",
    title: "Data Scientist",
    department: "Data",
    type: "Full-time",
    location: "Seattle, WA (Hybrid)",
    postedDate: "3 days ago",
    salary: "$130,000 - $160,000",
    description:
      "We're looking for a Data Scientist to help us extract insights from our data and build predictive models. You'll work closely with product and engineering teams to drive data-informed decisions.",
    responsibilities: [
      "Analyze large datasets to identify patterns and trends",
      "Build and deploy machine learning models",
      "Create dashboards and visualizations to communicate insights",
      "Collaborate with engineering team to implement data-driven features",
      "Stay current with latest developments in data science and machine learning",
    ],
    requirements: [
      "3+ years of experience in data science or related field",
      "Strong programming skills in Python and SQL",
      "Experience with data visualization tools (Tableau, PowerBI)",
      "Knowledge of machine learning frameworks (TensorFlow, PyTorch)",
      "Master's degree or PhD in Computer Science, Statistics, or related field",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Health, dental, and vision insurance",
      "Flexible work arrangements",
      "Unlimited PTO",
      "401(k) matching",
      "Professional development budget",
    ],
  },
  {
    id: "8",
    title: "Sales Development Representative",
    department: "Sales",
    type: "Full-time",
    location: "Boston, MA (Hybrid)",
    postedDate: "1 week ago",
    salary: "$60,000 - $80,000 + Commission",
    description:
      "We're seeking a Sales Development Representative to help grow our customer base. You'll be responsible for prospecting, qualifying leads, and setting up meetings for our account executives.",
    responsibilities: [
      "Prospect and qualify new sales opportunities",
      "Conduct outreach via email, phone, and social media",
      "Schedule meetings for account executives with qualified prospects",
      "Maintain accurate records in CRM system",
      "Stay up-to-date on product features and competitive landscape",
    ],
    requirements: [
      "1+ years of sales experience, preferably in B2B SaaS",
      "Strong communication and interpersonal skills",
      "Goal-oriented mindset with ability to work independently",
      "Experience with CRM software (Salesforce, HubSpot)",
      "Bachelor's degree in Business, Communications, or related field (preferred)",
    ],
    benefits: [
      "Competitive base salary plus commission structure",
      "Health, dental, and vision insurance",
      "Flexible work arrangements",
      "Generous PTO",
      "401(k) matching",
      "Professional development opportunities",
    ],
  },
  {
    id: "9",
    title: "Backend Engineer",
    department: "Engineering",
    type: "Full-time",
    location: "Remote",
    postedDate: "4 days ago",
    salary: "$120,000 - $150,000",
    description:
      "We're looking for a Backend Engineer to design and build scalable APIs and services. You'll work closely with frontend developers and other stakeholders to deliver robust solutions.",
    responsibilities: [
      "Design and implement scalable backend services and APIs",
      "Write clean, maintainable, and well-tested code",
      "Optimize database queries and application performance",
      "Collaborate with frontend developers to integrate APIs",
      "Participate in code reviews and technical discussions",
    ],
    requirements: [
      "4+ years of experience in backend development",
      "Strong proficiency in Node.js, Python, or similar languages",
      "Experience with SQL and NoSQL databases",
      "Knowledge of API design principles and best practices",
      "Familiarity with containerization and microservices architecture",
      "Bachelor's degree in Computer Science or related field (or equivalent experience)",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Health, dental, and vision insurance",
      "Remote-first work environment",
      "Unlimited PTO",
      "Home office stipend",
      "Professional development budget",
    ],
  },
];
