export const countries = [
  // Gulf Countries (GCC) - Starting with Saudi Arabia
  {
    value: "sa",
    label: "Saudi Arabia",
    code: "+966",
    placeholder: "5X XXX XXXX",
  },
  {
    value: "ae",
    label: "United Arab Emirates",
    code: "+971",
    placeholder: "5X XXX XXXX",
  },
  {
    value: "kw",
    label: "Kuwait",
    code: "+965",
    placeholder: "5XXX XXXX",
  },
  {
    value: "qa",
    label: "Qatar",
    code: "+974",
    placeholder: "3XXX XXXX",
  },
  {
    value: "bh",
    label: "Bahrain",
    code: "+973",
    placeholder: "3XXX XXXX",
  },
  {
    value: "om",
    label: "Oman",
    code: "+968",
    placeholder: "9XXX XXXX",
  },

  // Other Arab Countries
  {
    value: "eg",
    label: "Egypt",
    code: "+20",
    placeholder: "1XX XXX XXXX",
  },
  {
    value: "jo",
    label: "Jordan",
    code: "+962",
    placeholder: "7XXX XXXX",
  },
  {
    value: "iq",
    label: "Iraq",
    code: "+964",
    placeholder: "7XX XXX XXXX",
  },
  {
    value: "sy",
    label: "Syria",
    code: "+963",
    placeholder: "9XX XXX XXX",
  },
  {
    value: "lb",
    label: "Lebanon",
    code: "+961",
    placeholder: "7X XXX XXX",
  },
  {
    value: "ye",
    label: "Yemen",
    code: "+967",
    placeholder: "7XX XXX XXX",
  },
  {
    value: "ps",
    label: "Palestine",
    code: "+970",
    placeholder: "5XX XXX XXX",
  },
  {
    value: "sd",
    label: "Sudan",
    code: "+249",
    placeholder: "9X XXX XXXX",
  },
  {
    value: "ly",
    label: "Libya",
    code: "+218",
    placeholder: "9X XXX XXXX",
  },
  {
    value: "tn",
    label: "Tunisia",
    code: "+216",
    placeholder: "2X XXX XXX",
  },
  {
    value: "dz",
    label: "Algeria",
    code: "+213",
    placeholder: "5XX XXX XXX",
  },
  {
    value: "ma",
    label: "Morocco",
    code: "+212",
    placeholder: "6XX XXX XXX",
  },
  {
    value: "mr",
    label: "Mauritania",
    code: "+222",
    placeholder: "3XXX XXXX",
  },
  {
    value: "so",
    label: "Somalia",
    code: "+252",
    placeholder: "6X XXX XXX",
  },
  {
    value: "dj",
    label: "Djibouti",
    code: "+253",
    placeholder: "7X XX XX XX",
  },
  {
    value: "km",
    label: "Comoros",
    code: "+269",
    placeholder: "3XX XXXX",
  },

  // Rest of the World (Alphabetically)
  {
    value: "af",
    label: "Afghanistan",
    code: "+93",
    placeholder: "7X XXX XXXX",
  },
  {
    value: "al",
    label: "Albania",
    code: "+355",
    placeholder: "6X XXX XXXX",
  },
  {
    value: "ad",
    label: "Andorra",
    code: "+376",
    placeholder: "3XX XXX",
  },
  {
    value: "ao",
    label: "Angola",
    code: "+244",
    placeholder: "9XX XXX XXX",
  },
  {
    value: "ar",
    label: "Argentina",
    code: "+54",
    placeholder: "11 XXXX XXXX",
  },
  {
    value: "am",
    label: "Armenia",
    code: "+374",
    placeholder: "XX XXX XXX",
  },
  {
    value: "au",
    label: "Australia",
    code: "+61",
    placeholder: "4XX XXX XXX",
  },
  {
    value: "at",
    label: "Austria",
    code: "+43",
    placeholder: "6XX XXX XXX",
  },
  {
    value: "az",
    label: "Azerbaijan",
    code: "+994",
    placeholder: "4X XXX XXXX",
  },
  {
    value: "bs",
    label: "Bahamas",
    code: "+1242",
    placeholder: "XXX XXXX",
  },
  {
    value: "bd",
    label: "Bangladesh",
    code: "+880",
    placeholder: "1XXX XXXXXX",
  },
  {
    value: "by",
    label: "Belarus",
    code: "+375",
    placeholder: "XX XXX XXXX",
  },
  {
    value: "be",
    label: "Belgium",
    code: "+32",
    placeholder: "4XX XX XX XX",
  },
  {
    value: "br",
    label: "Brazil",
    code: "+55",
    placeholder: "11 9XXXX XXXX",
  },
  {
    value: "bg",
    label: "Bulgaria",
    code: "+359",
    placeholder: "8XX XXX XXX",
  },
  {
    value: "kh",
    label: "Cambodia",
    code: "+855",
    placeholder: "1X XXX XXX",
  },
  {
    value: "ca",
    label: "Canada",
    code: "+1",
    placeholder: "(XXX) XXX-XXXX",
  },
  {
    value: "cn",
    label: "China",
    code: "+86",
    placeholder: "1XX XXXX XXXX",
  },
  {
    value: "dk",
    label: "Denmark",
    code: "+45",
    placeholder: "XX XX XX XX",
  },
  {
    value: "fi",
    label: "Finland",
    code: "+358",
    placeholder: "4X XXX XXXX",
  },
  {
    value: "fr",
    label: "France",
    code: "+33",
    placeholder: "6 XX XX XX XX",
  },
  {
    value: "de",
    label: "Germany",
    code: "+49",
    placeholder: "15X XXXXXXX",
  },
  {
    value: "gr",
    label: "Greece",
    code: "+30",
    placeholder: "6XX XXX XXXX",
  },
  {
    value: "hk",
    label: "Hong Kong",
    code: "+852",
    placeholder: "XXXX XXXX",
  },
  {
    value: "hu",
    label: "Hungary",
    code: "+36",
    placeholder: "3X XXX XXXX",
  },
  {
    value: "is",
    label: "Iceland",
    code: "+354",
    placeholder: "XXX XXXX",
  },
  {
    value: "in",
    label: "India",
    code: "+91",
    placeholder: "9XXXXXXXXX",
  },
  {
    value: "id",
    label: "Indonesia",
    code: "+62",
    placeholder: "8XX-XXX-XXX",
  },
  {
    value: "ir",
    label: "Iran",
    code: "+98",
    placeholder: "9XX XXX XXXX",
  },
  {
    value: "ie",
    label: "Ireland",
    code: "+353",
    placeholder: "8X XXX XXXX",
  },
  {
    value: "it",
    label: "Italy",
    code: "+39",
    placeholder: "3XX XXX XXXX",
  },
  {
    value: "jp",
    label: "Japan",
    code: "+81",
    placeholder: "90-XXXX-XXXX",
  },
  {
    value: "my",
    label: "Malaysia",
    code: "+60",
    placeholder: "1X-XXX XXXX",
  },
  {
    value: "mx",
    label: "Mexico",
    code: "+52",
    placeholder: "1XX XXX XXXX",
  },
  {
    value: "nl",
    label: "Netherlands",
    code: "+31",
    placeholder: "6 XXXXXXXX",
  },
  {
    value: "nz",
    label: "New Zealand",
    code: "+64",
    placeholder: "2X XXX XXXX",
  },
  {
    value: "no",
    label: "Norway",
    code: "+47",
    placeholder: "4XX XX XXX",
  },
  {
    value: "pk",
    label: "Pakistan",
    code: "+92",
    placeholder: "3XX XXXXXXX",
  },
  {
    value: "ph",
    label: "Philippines",
    code: "+63",
    placeholder: "9XX XXX XXXX",
  },
  {
    value: "pl",
    label: "Poland",
    code: "+48",
    placeholder: "5XX XXX XXX",
  },
  {
    value: "pt",
    label: "Portugal",
    code: "+351",
    placeholder: "9XX XXX XXX",
  },
  {
    value: "ro",
    label: "Romania",
    code: "+40",
    placeholder: "7XX XXX XXX",
  },
  {
    value: "ru",
    label: "Russia",
    code: "+7",
    placeholder: "9XX XXX-XX-XX",
  },
  {
    value: "sg",
    label: "Singapore",
    code: "+65",
    placeholder: "XXXX XXXX",
  },
  {
    value: "za",
    label: "South Africa",
    code: "+27",
    placeholder: "8X XXX XXXX",
  },
  {
    value: "kr",
    label: "South Korea",
    code: "+82",
    placeholder: "10-XXXX-XXXX",
  },
  {
    value: "es",
    label: "Spain",
    code: "+34",
    placeholder: "6XX XXX XXX",
  },
  {
    value: "se",
    label: "Sweden",
    code: "+46",
    placeholder: "7X-XXX XX XX",
  },
  {
    value: "ch",
    label: "Switzerland",
    code: "+41",
    placeholder: "7X XXX XX XX",
  },
  {
    value: "tw",
    label: "Taiwan",
    code: "+886",
    placeholder: "9XX XXX XXX",
  },
  {
    value: "th",
    label: "Thailand",
    code: "+66",
    placeholder: "8X XXX XXXX",
  },
  {
    value: "tr",
    label: "Turkey",
    code: "+90",
    placeholder: "5XX XXX XXXX",
  },
  {
    value: "gb",
    label: "United Kingdom",
    code: "+44",
    placeholder: "7XXX XXXXXX",
  },
  {
    value: "us",
    label: "United States",
    code: "+1",
    placeholder: "(XXX) XXX-XXXX",
  },
  {
    value: "vn",
    label: "Vietnam",
    code: "+84",
    placeholder: "9XX XXX XXX",
  },
];
