export const countries = [
  // Gulf Countries (GCC) - Starting with Saudi Arabia
  {
    value: "sa",
    label: "Saudi Arabia",
    arabic_label: "المملكة العربية السعودية",
    code: "+966",
    placeholder: "5X XXX XXXX",
  },
  {
    value: "ae",
    label: "United Arab Emirates",
    arabic_label: "الإمارات العربية المتحدة",
    code: "+971",
    placeholder: "5X XXX XXXX",
  },
  {
    value: "kw",
    label: "Kuwait",
    arabic_label: "الكويت",
    code: "+965",
    placeholder: "5XXX XXXX",
  },
  {
    value: "qa",
    label: "Qatar",
    arabic_label: "قطر",
    code: "+974",
    placeholder: "3XXX XXXX",
  },
  {
    value: "bh",
    label: "Bahrain",
    arabic_label: "البحرين",
    code: "+973",
    placeholder: "3XXX XXXX",
  },
  {
    value: "om",
    label: "Oman",
    arabic_label: "عمان",
    code: "+968",
    placeholder: "9XXX XXXX",
  },

  // Other Arab Countries
  {
    value: "eg",
    label: "Egypt",
    arabic_label: "مصر",
    code: "+20",
    placeholder: "1XX XXX XXXX",
  },
  {
    value: "jo",
    label: "Jordan",
    arabic_label: "الأردن",
    code: "+962",
    placeholder: "7XXX XXXX",
  },
  {
    value: "iq",
    label: "Iraq",
    arabic_label: "العراق",
    code: "+964",
    placeholder: "7XX XXX XXXX",
  },
  {
    value: "sy",
    label: "Syria",
    arabic_label: "سوريا",
    code: "+963",
    placeholder: "9XX XXX XXX",
  },
  {
    value: "lb",
    label: "Lebanon",
    arabic_label: "لبنان",
    code: "+961",
    placeholder: "7X XXX XXX",
  },
  {
    value: "ye",
    label: "Yemen",
    arabic_label: "اليمن",
    code: "+967",
    placeholder: "7XX XXX XXX",
  },
  {
    value: "ps",
    label: "Palestine",
    arabic_label: "فلسطين",
    code: "+970",
    placeholder: "5XX XXX XXX",
  },
  {
    value: "sd",
    label: "Sudan",
    arabic_label: "السودان",
    code: "+249",
    placeholder: "9X XXX XXXX",
  },
  {
    value: "ly",
    label: "Libya",
    arabic_label: "ليبيا",
    code: "+218",
    placeholder: "9X XXX XXXX",
  },
  {
    value: "tn",
    label: "Tunisia",
    arabic_label: "تونس",
    code: "+216",
    placeholder: "2X XXX XXX",
  },
  {
    value: "dz",
    label: "Algeria",
    arabic_label: "الجزائر",
    code: "+213",
    placeholder: "5XX XXX XXX",
  },
  {
    value: "ma",
    label: "Morocco",
    arabic_label: "المغرب",
    code: "+212",
    placeholder: "6XX XXX XXX",
  },
  {
    value: "mr",
    label: "Mauritania",
    arabic_label: "موريتانيا",
    code: "+222",
    placeholder: "3XXX XXXX",
  },
  {
    value: "so",
    label: "Somalia",
    arabic_label: "الصومال",
    code: "+252",
    placeholder: "6X XXX XXX",
  },
  {
    value: "dj",
    label: "Djibouti",
    arabic_label: "جيبوتي",
    code: "+253",
    placeholder: "7X XX XX XX",
  },
  {
    value: "km",
    label: "Comoros",
    arabic_label: "جزر القمر",
    code: "+269",
    placeholder: "3XX XXXX",
  },

  // Rest of the World (Alphabetically)
  {
    value: "af",
    label: "Afghanistan",
    arabic_label: "أفغانستان",
    code: "+93",
    placeholder: "7X XXX XXXX",
  },
  {
    value: "al",
    label: "Albania",
    arabic_label: "ألبانيا",
    code: "+355",
    placeholder: "6X XXX XXXX",
  },
  {
    value: "ad",
    label: "Andorra",
    arabic_label: "أندورا",
    code: "+376",
    placeholder: "3XX XXX",
  },
  {
    value: "ao",
    label: "Angola",
    arabic_label: "أنغولا",
    code: "+244",
    placeholder: "9XX XXX XXX",
  },
  {
    value: "ar",
    label: "Argentina",
    arabic_label: "الأرجنتين",
    code: "+54",
    placeholder: "11 XXXX XXXX",
  },
  {
    value: "am",
    label: "Armenia",
    arabic_label: "أرمينيا",
    code: "+374",
    placeholder: "XX XXX XXX",
  },
  {
    value: "au",
    label: "Australia",
    arabic_label: "أستراليا",
    code: "+61",
    placeholder: "4XX XXX XXX",
  },
  {
    value: "at",
    label: "Austria",
    arabic_label: "النمسا",
    code: "+43",
    placeholder: "6XX XXX XXX",
  },
  {
    value: "az",
    label: "Azerbaijan",
    arabic_label: "أذربيجان",
    code: "+994",
    placeholder: "4X XXX XXXX",
  },
  {
    value: "bs",
    label: "Bahamas",
    arabic_label: "البهاماس",
    code: "+1242",
    placeholder: "XXX XXXX",
  },
  {
    value: "bd",
    label: "Bangladesh",
    arabic_label: "بنغلاديش",
    code: "+880",
    placeholder: "1XXX XXXXXX",
  },
  {
    value: "by",
    label: "Belarus",
    arabic_label: "بيلاروس",
    code: "+375",
    placeholder: "XX XXX XXXX",
  },
  {
    value: "be",
    label: "Belgium",
    arabic_label: "بلجيكا",
    code: "+32",
    placeholder: "4XX XX XX XX",
  },
  {
    value: "br",
    label: "Brazil",
    arabic_label: "البرازيل",
    code: "+55",
    placeholder: "11 9XXXX XXXX",
  },
  {
    value: "bg",
    label: "Bulgaria",
    arabic_label: "بلغاريا",
    code: "+359",
    placeholder: "8XX XXX XXX",
  },
  {
    value: "kh",
    label: "Cambodia",
    arabic_label: "كمبوديا",
    code: "+855",
    placeholder: "1X XXX XXX",
  },
  {
    value: "ca",
    label: "Canada",
    arabic_label: "كندا",
    code: "+1",
    placeholder: "(XXX) XXX-XXXX",
  },
  {
    value: "cn",
    label: "China",
    arabic_label: "الصين",
    code: "+86",
    placeholder: "1XX XXXX XXXX",
  },
  {
    value: "dk",
    label: "Denmark",
    arabic_label: "الدنمارك",
    code: "+45",
    placeholder: "XX XX XX XX",
  },
  {
    value: "fi",
    label: "Finland",
    arabic_label: "فنلندا",
    code: "+358",
    placeholder: "4X XXX XXXX",
  },
  {
    value: "fr",
    label: "France",
    arabic_label: "فرنسا",
    code: "+33",
    placeholder: "6 XX XX XX XX",
  },
  {
    value: "de",
    label: "Germany",
    arabic_label: "ألمانيا",
    code: "+49",
    placeholder: "15X XXXXXXX",
  },
  {
    value: "gr",
    label: "Greece",
    arabic_label: "اليونان",
    code: "+30",
    placeholder: "6XX XXX XXXX",
  },
  {
    value: "hk",
    label: "Hong Kong",
    arabic_label: "هونغ كونغ",
    code: "+852",
    placeholder: "XXXX XXXX",
  },
  {
    value: "hu",
    label: "Hungary",
    arabic_label: "المجر",
    code: "+36",
    placeholder: "3X XXX XXXX",
  },
  {
    value: "is",
    label: "Iceland",
    arabic_label: "آيسلندا",
    code: "+354",
    placeholder: "XXX XXXX",
  },
  {
    value: "in",
    label: "India",
    arabic_label: "الهند",
    code: "+91",
    placeholder: "9XXXXXXXXX",
  },
  {
    value: "id",
    label: "Indonesia",
    arabic_label: "إندونيسيا",
    code: "+62",
    placeholder: "8XX-XXX-XXX",
  },
  {
    value: "ir",
    label: "Iran",
    arabic_label: "إيران",
    code: "+98",
    placeholder: "9XX XXX XXXX",
  },
  {
    value: "ie",
    label: "Ireland",
    arabic_label: "أيرلندا",
    code: "+353",
    placeholder: "8X XXX XXXX",
  },
  {
    value: "it",
    label: "Italy",
    arabic_label: "إيطاليا",
    code: "+39",
    placeholder: "3XX XXX XXXX",
  },
  {
    value: "jp",
    label: "Japan",
    arabic_label: "اليابان",
    code: "+81",
    placeholder: "90-XXXX-XXXX",
  },
  {
    value: "my",
    label: "Malaysia",
    arabic_label: "ماليزيا",
    code: "+60",
    placeholder: "1X-XXX XXXX",
  },
  {
    value: "mx",
    label: "Mexico",
    arabic_label: "المكسيك",
    code: "+52",
    placeholder: "1XX XXX XXXX",
  },
  {
    value: "nl",
    label: "Netherlands",
    arabic_label: "هولندا",
    code: "+31",
    placeholder: "6 XXXXXXXX",
  },
  {
    value: "nz",
    label: "New Zealand",
    arabic_label: "نيوزيلندا",
    code: "+64",
    placeholder: "2X XXX XXXX",
  },
  {
    value: "no",
    label: "Norway",
    arabic_label: "نرويج",
    code: "+47",
    placeholder: "4XX XX XXX",
  },
  {
    value: "pk",
    label: "Pakistan",
    arabic_label: "باكستان",
    code: "+92",
    placeholder: "3XX XXXXXXX",
  },
  {
    value: "ph",
    label: "Philippines",
    arabic_label: "الفلبين",
    code: "+63",
    placeholder: "9XX XXX XXXX",
  },
  {
    value: "pl",
    label: "Poland",
    arabic_label: "بولندا",
    code: "+48",
    placeholder: "5XX XXX XXX",
  },
  {
    value: "pt",
    label: "Portugal",
    arabic_label: "البرتغال",
    code: "+351",
    placeholder: "9XX XXX XXX",
  },
  {
    value: "ro",
    label: "Romania",
    arabic_label: "رومانيا",
    code: "+40",
    placeholder: "7XX XXX XXX",
  },
  {
    value: "ru",
    label: "Russia",
    arabic_label: "روسيا",
    code: "+7",
    placeholder: "9XX XXX-XX-XX",
  },
  {
    value: "sg",
    label: "Singapore",
    arabic_label: "سنغافورة",
    code: "+65",
    placeholder: "XXXX XXXX",
  },
  {
    value: "za",
    label: "South Africa",
    arabic_label: "جنوب أفريقيا",
    code: "+27",
    placeholder: "8X XXX XXXX",
  },
  {
    value: "kr",
    label: "South Korea",
    arabic_label: "كوريا الجنوبية",
    code: "+82",
    placeholder: "10-XXXX-XXXX",
  },
  {
    value: "es",
    label: "Spain",
    arabic_label: "إسبانيا",
    code: "+34",
    placeholder: "6XX XXX XXX",
  },
  {
    value: "se",
    label: "Sweden",
    arabic_label: "السويد",
    code: "+46",
    placeholder: "7X-XXX XX XX",
  },
  {
    value: "ch",
    label: "Switzerland",
    arabic_label: "سويسرا",
    code: "+41",
    placeholder: "7X XXX XX XX",
  },
  {
    value: "tw",
    label: "Taiwan",
    arabic_label: "تايوان",
    code: "+886",
    placeholder: "9XX XXX XXX",
  },
  {
    value: "th",
    label: "Thailand",
    arabic_label: "تايلاند",
    code: "+66",
    placeholder: "8X XXX XXXX",
  },
  {
    value: "tr",
    label: "Turkey",
    arabic_label: "تركيا",
    code: "+90",
    placeholder: "5XX XXX XXXX",
  },
  {
    value: "gb",
    label: "United Kingdom",
    arabic_label: "المملكة المتحدة",
    code: "+44",
    placeholder: "7XXX XXXXXX",
  },
  {
    value: "us",
    label: "United States",
    arabic_label: "الولايات المتحدة",
    code: "+1",
    placeholder: "(XXX) XXX-XXXX",
  },
  {
    value: "vn",
    label: "Vietnam",
    arabic_label: "فيتنام",
    code: "+84",
    placeholder: "9XX XXX XXX",
  },
];
